<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Lapis.Evaluator/Lapis.Evaluator.csproj" />
    <ProjectReference Include="../../src/Lapis.TypeChecker/Lapis.TypeChecker.csproj" />
    <ProjectReference Include="../../src/Lapis.Desugar/Lapis.Desugar.csproj" />
    <ProjectReference Include="../../src/Lapis.Parser/Lapis.Parser.csproj" />
    <ProjectReference Include="../../src/Lapis.Runtime/Lapis.Runtime.csproj" />
  </ItemGroup>

</Project>
